### ISSUE TITLE
Format readme

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/tizen_api#1]
The readme file contains code that isn't being specified as code so the formatting is off.

Please fix it

**Comment by M4dhav** [comment]
I'll help you out with this, give me some time

**Comment by guyluz11** [comment]
Sounds great, waiting for pr.

Also a star to the project would be nice.

I will try to upload it to pub.dev today

**Comment by guyluz11** [comment]
Thanks
Closing
