### ISSUE TITLE
Automatic initializetion

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/tizen_api#3]
For the code to work users currently need to initialize in the main function using TizenHelperMethods.initialize();

It would be nice if we can make this process automatic

**Comment by M4dhav** [comment]
I would like to help you out with this, could you please tell me how I can test the application locally? I don't have a TV on hand to test it, are there any alternatives for developmental purposes?

**Comment by guyluz11** [comment]
Hey @M4dhav 
Unfortunately there are no alternatives that I know of but I do have an interesting idea for you.

I understand that you want to help dart open source projects and develop experience right?. 
This repo is planned to be part of another project that might pick your interest and does not require a specific device to use and enjoy.
It is an app called Infinite Horizons that is helping to enhance learning session efficiency for students and workers.
With the help of studies and known methods we help people to increase concentration, better remember study material, maintain healthy lifestyles and more.

It is still in its first phase so a good time to join and advance with the project.
It will be amazing to see you taking part in the project since its goal is to help humanity.

Here is a link to the github: https://github.com/guyluz11/infinite_horizons
